### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tanupandey28** [techinfo-youtube/Doctor-appointmnet-system-mern-project#2]
getting axios error while registering the user error:500 what should i do?
![WhatsApp Image 2023-06-22 at 6 12 36 PM](https://github.com/techinfo-youtube/Doctor-appointmnet-system-mern-project/assets/67185714/f33a2cbc-773d-46ec-8121-6f9719f3aa51)

**Comment by techinfo-youtube** [comment]
what error message is showing ? may be you missed something or spelling mistake have you cross check code from source code....
also please check that API request preview and response in the network tab
